Math/gcd/gcd.cpp

Implement GCD in C++

---

Sorting/CountingSort.java
Sorting/RadixSort.java

Added CountingSort and RadixSort for java

Sorting and Searching algorithms

---

DP/Coin Change Problem/CoinChangeProblem.cpp

CoinChangeProblem added to DP

---

DP/Fibonacci/Fibonacci.py

Bottom up Approach for Fibonacci series

---

Math/modular_multiplicative_inverse/mmi.cpp

This adds a program to calculate m which satisfies the following equation:
(x*m) % n = 1
if provided x and n

added a program to calculate the modular multiplicative inverse

---

String/Palindrome/is_palindrome.py

Implemented Palindrome check algorithm in Python

---

Math/lowest_common_multiple/lcm.py

Implemented Lowest Common Multiple algorithm in Python

---

Math/sieve_of_eratosthenes/eratosthenes.py

For issue number [3](https://github.com/matthewsamuel95/ACM-ICPC-Algorithms/issues/3)

Implement the Seive of Eratosthenes in python

---

BackTracking/KnightsTour/knightstour.cpp
BackTracking/NQueens/nqueens.c

In reference to the issue #7. Will add more.

Added Backtracking algorithms nqueens and knightsTour

---

Graph/BellmanFordSSSP/BellmanFordSSSP.cpp
Graph/DijkstrasSPT/DijkstrasUsingAdjcencyList.cpp
Graph/DijkstrasSPT/DijkstrasUsingMatrix.cpp
Graph/KruskalsMST/KruskalsMST.cpp
Graph/PrimsMST/PrimsMSTusingAdjacencyList.cpp
Graph/PrimsMST/PrimsMSTusingMatrix.cpp
Graph/README.md

In reference to the issue #55 added BellmanFord, Kruskals, Dijkstras and Prims algorithm implementation in cpp

Added a few graph algorithms

---

Graph/TopoSort/toposort.c

Added toposort in c

---

DP/LongestCommonSubsequence/LCS.cpp

Added lcs in cpp

---

Greedy/Kruskal’sMinimumSpanningTree/Kruskal’sMinimumSpanningTree.cpp
Math/sieve_of_eratosthenes/SegmentedSieve.cpp

Added Segmented sieve in cpp

---

NetworkFlow/FordFulkerson/FordFulkerson.cpp

Added Ford-Fulkerson in Netwok Flow Algorithm

---

DP/LongestIncreasingSubsequence/LIS.c

added LIS in c

---

Graph/floydWarshall.cpp

All Pair Shortest Distance O(V<sup>3</sup>)

floydWarshall.cpp

---

DP/ShortestUncommonSubsequence/SUS.cpp

solve shortest uncommon subsequence

---

Graph/Detect_Cycle/detect_cycle_undirected.cpp

Fixes #9 
Added an algo to detect cycles in an undirected graph

Added graph algo to detect cycles in a graph

---

DP/LongestIncreasingSubsequence/LIS_(nlogn).cpp

Fixes #123 
Added Algo for the Longest Increasing Subsequence with N log N complexity

Added algo for LIS - O(N log N)

---

Search/LinearSearch/lsearch.cpp

Code is having a better Understanding, if compared to existing one.

Updation lsearch.cpp

---

NetworkFlow/Dinic/Dinic.cpp

#138: Dinic's algorithm for maximum flow problem

[Network Flow] Dinic's algorithm added

---

String/Balanced Parentheses/README.md
String/Balanced Parentheses/balanced_parantheses.cpp

added balance parantheses

---

Math/floor_sqrt/sqrt.py

Adding sqrt function using Binary search Algorithm. Due to which complexity is  O(Log x).

Adding sqrt function in python

---

NetworkFlow/EdmundKarp/README.md
NetworkFlow/EdmundKarp/edmund_karp.py

added edmund karp

---

BFS/bfs.py

Python implementation of Breadth First Search.

Added bfs.py - Python implementation of BFS.

---

Math/squareroot/sqroot.c

Created a program to calculate square root of a number in C language.

Created sq_root.c

---

Math/NextPow2/nextpow2.cpp

Add Implementation of Next Power of 2

---

Sorting/SelectionSort/C/Selection_sort.c

Added a new method of sorting in C language in appropriate location

Created Selection_sort.c

---

BitManipulation/count_ones/Method2.c

Added another method, programmed in C Language

Created Method2.c

---

BitManipulation/count_ones/Count_Ones.c

Created Count_Ones.c

---

BitManipulation/Checking_power_of_2/Checkpowerof2.c

Created CheckPowerof2.c

---

String/Palindrome/C/isPalindrome.c

Created isPalindrome.c

---

Math/Power/power.cpp

Issue #236 
The power function is implemented in cpp without the library function with clean coding...

Power function is implemented in cpp

---

Math/3_Sum_square_complexity/3numbers.cpp

Solution for problem - Sum of 3 numbers in an array in O(n^2)

issue #231

---

Math/factors/factor.cpp

created prime factors

---

Math/All factors of a given Number/All factors of a given Number.cpp

Add the cpp file to get All factors of a given Number related to #263

Create All factors of a given Number.cpp

---

Graph/Centroid Decomposition/centroid_decomposition.cpp

Centroid Decomposition - Graph
https://threads-iiith.quora.com/Centroid-Decomposition-of-a-Tree

Created Centroid Decomposition

---

Data Structures/Implement Stack Using Queues/stackUsingQueues.cpp
Data Structures/Implement queue using stack/queueUsingStack.cpp

Added code for creation of stack using queues

---

String/Top_K_Frequent_Words/README.md
String/Top_K_Frequent_Words/Top_K_Frequent_Words.cpp

Top K Frequent Words

---

String/Top_K_Frequent_Words/top_k_frequent_words.py

Python version of the 'top K frequent words' (fixing issue #277)

Added Python version for 'Top K frequent words'

---

Data Structures/QueueFromStack_StackFromQueue/Cpp/queue_from_stack.cpp
Data Structures/QueueFromStack_StackFromQueue/Cpp/stack_from_queue.cpp

Added cpp implementation for queue using stack and stack using queue.
Address issue #279  and #278

added cpp implementation for queue<->stack

---

README.md

Fixed visual typo

---

Graph/bridges/bridges.cpp

code to find bridges in a graph

bridges in a graph

---

Graph/Articulation_points/ap.cpp

Added code for finding articulation Point in a graph

articulation points

---

Greedy/EqualizingBitStrings/EqualizeBitStrings.cpp
Greedy/EqualizingBitStrings/ProblemStatement.md
contributing.md

Added the file contributing.md on how to make a pull request

How to make a pull request

---

Greedy/Greedy_Graph_Coloring/GreedyGraphColoring.cpp

A Greedy algorithm that never uses more than D+1 colors to color all the vertices of a graph, where D is the maximum degree in the graph. This is coded in C++14.

A greedy algorithm for graph coloring using D+1 Colors

---

Data Structures/SinglyLinkedList/Deletion_Every_Alternate_Node.c

add deletion of every alternate node element in a singly linked list

add deletion of every alternate node in a SinglyLinkedList

---

Data Structures/disjointset/findunion.cpp
Math/convuxhull/convuxhull.cpp
Math/convuxhull/grahamscan.cpp

Will add readme for all the algorithms after contributing everything

jarvis convux hull

---

Math/Factorization/findFactors.cpp

not a listed issue - but I couldn't help but see how I would code it up.

creates program to do factorization

---

Hashing/3_Sum/threeSum.py

added solution for 3_Sum

---

BitManipulation/swap_bits/shorter_sawp.cpp
BitManipulation/swap_bits/swap.cpp

Bit algorithm : Swap bits in a given no

Sahil0071_bit

---

Sorting/bubble sort/c/Bubble_Sort.c

Best Case: **O(N)** using a flag to optimize solution.

Optimized Bubble Sort

---

String/String Automaton/suffix_automaton.cpp

This PR adds Suffix Automaton Algorithm.

Add suffix automaton

---

Graph/EulerPath/euler_path.cpp

This PR adds euler path in graph algorithm.

Add euler path in graph

---

Search/BinarySearch/BinarySearch.java

Implementation of Binary Search in Java

Added Binary Search in Java

---

Sorting/bubble sort/python/BubbleSort.py

Added python version of bubble sort algorithm.

add python bubble sort

---

Data Structures/Fenwick_tree/point_update_range_queries.cpp
Data Structures/Fenwick_tree/range_update_point_queries.cpp

Fenwick Tree with variations -: 
1. Point update and range queries
2. Range update and point queries

Added fenwick tree with variations

---

DP/game_of_sum/10891.cpp

game_of_sum

---

String/Anagram/is-anagram.js

adds a javascript implemention of checking whether two strings are anagrams

 ✨(String/Anagram) adding anagram-checking in javascript

---

DP/Fibonacci/FiboDP.java
DP/Knapsack/Knapsack.java

Hi,
I have added  java code for Fibonacci and Knapsack in Dynamic Programming.

Add Fibonacci and Knapsack java code in DP folder

---

NetworkFlow/GoldbergTarjan/GoldbergTarjan.cc

Added code for push - relabel max flow, with move-to-front selection rule.
Works in O(n^3) time for a network with n nodes.

Added push-relabel max flow.

---

Search/LinearSearch/linear_search.py

This is an implementation of linear search algorithm in python.

linear_search.py

---

BackTracking/NQueens/nqueen.java

here is the solution to the n queen problem in java. solved using backtracking

nqueen.java

---

Sorting/bubble sort/js/BubbleSort.js

Hi Guys,
Hope I can help with my knowledge of js, I know is a weird language to do competitive programming but it can be done and it can help others :)
I added the bubble sort algorithm, if you think is a good idea I could implement a ton of other algorithms in js.
Thanks :)

Added BubbleSort algorithm in js

---

BFS/python/bfs.py

Change:
- Added a simple bfs in python

Added Breadth First Search in python

---

README.md
Sorting/CocktailShakerSort/README.md
Sorting/CocktailShakerSort/cocktail_shaker_sort.js

Add cocktail shaker sort

---

Math/Fast Exponentiation with Mod/fast_expo_with_mod.py

This commit is simple enough: Adds fast_expo_with_mod.py, that implements fast exponentiation in modulo.

Adds fast exponentiation in python

---

DP/LongestBitonicSubseq/longest_bitonic_subsequence.cpp
README.md

Updated Readme.md

---

Sorting/Pancake sorting/pancake.c

added pancake sorting algorithm in c

pancake in c

---

Math/AllPermutations/permutation.cpp
README.md

AllPermutation.cpp: calculate and print all permutations of a vector<int>

Add "AllPermutation" Algorithm

---

Data Structures/Linked List/SinglyLinkedList.cpp

Program which implements the euclidean algorithm (in other words, the gcd algorithm).

Middle Node in Singly Linked List

---

String/Palindrome/Javascript/isPalindrome.js

Checks to see if it's a palindrome in JavaScript

PalindromeCheck

---

Search/hashing/2_Sum/sum_pair.py

Given an array and a number, find all the pairs whose sum is equal to the given number

Add python implementation of pair sum problem

---

README.md
String/ParsingArithmetic/ShuntingYard.cpp

I updated the table of contents now

Cpp parsing of simple arithmetic expressions (shunting yard algorithm)

---

Sorting/bubble sort/cpp/buubleDesc.cpp

Added bubble sort descending.

---

String/KMP/kmp.cpp

A simple kmp algorithm implementation in c++

added kmp algorithm for string matching

---

Search/BinarySearch/binary_search_javascript.js

I found it interesting to add more variant language as a part to participate in Hacktoberfest, and in this case i'm using Javascript.
As for example, i'm using sorted array.
`var arrays = [4,16,20,26,30,50,80];`
and for the execution code i'm using this part,
`console.log(binary_search(4))`
`console.log(binary_search(70))`
as for the result is,
`0`
`it's not exist`

New Language for Binary Search (JavaScript)

---

Math/Power/power.py

added Math/Power implementation and test in python

added Math/Power implementation and test in python

---

BST/README.md

Information how binary search tree is presented, and what values are stored in nodes.

Added information/documentation about BST into README.md

---

Sorting/bubble sort/README.md

I added a brief note on the algorithm of Bubble Sort with a visualization. The description is added in  a README.md file in Bubble Sort folder.

Added a description to Bubble Sort

---

Data Structures/disjointset/ConnectedComponent/ConnectedComponent.cpp

Implements DSU as a class and performs path compression

Created ConnectedComponent.cpp

---

DP/Egg Dropping Puzzle/egg_dropping_puzzle.cpp
DP/Tiling Problem/tiling.cpp
Search/EcponentialSearch/exponentialsearch.cpp

Added exponential search
Added Tiling Problem
Added Egg Dropping Puzzle

Added  tiling problem and egg dropping in dp and exponential search

---

DP/Recursive_Staircase_Problem/recursive_staircase_problem_python_steps_DP.py

Added new coding problem

---

Math/Power_For_Huge_Num/Power_Huge.cpp
Math/Power_For_Huge_Num/Power_Huge.java

Added new Algorithms to compute power for such numbers whose answer is too big(For instance 1 followed by thousand zeroes).
Using old multiplicatiion method will render invalid result for such
huge numbers(To be presise one would get 0 in case of C++14).
And such algoritham is very vital for contest like ACM-ICPC.

Added Algorithms to compute power for Huge Number

---

DP/Floyd Warshall Algorithm/floyd_warshall.py

An implementation of the Floyd Warshall Algorithm in Python to solve All-Pairs Shortest Path Problem

Created Floyd Warshall Algorithm in Python

---

Greedy/Kruskal’sMinimumSpanningTree/Kruskal’sMinimumSpanningTree.py

Python implementation of Kruskal's Algorithm to find the Minimum Spanning Tree in a graph

Add Kruskal’sMinimumSpanningTree for Python

---

Search/BinarySearch/binary_search_iterative.py

thought would be cool to have an iterative implementation of BS on python :)

added an iterative implementation of binary search

---

BitManipulation/count_ones/count_ones.cpp

counts correct number of bits. more specifically, the number of ones.

count_ones c++ done

---

MachineLearning/Perceptron/README.md
MachineLearning/Perceptron/simple_perceptron.py
README.md

FIXED: Added a simple perceptron implementation 

---

Math/gcd/gcd.java

Added a program to find the GCD using Euclidean Algorithm in Java.

Added GCD with Euclidean Algo in Java

---

Geometry 2D/Lines Intersection/lines_intersection.cpp
README.md

It is hard to find any official ACM ICPC competition without any problem on geometry.
With this pull request I would like to start a new flow where open source community could collect all common used implementations related to this topic.

Add Geometry in 2D section and source code for line intersection.

---

Math/last_digit_exp/Python/LastDigitOfExp.py

I implemented the same algorithm as the root readme.

Added last digit of exp python script

---

Math/Palindrome/Palindrome.py

same as the title. Please do review.

adding a python script to check if a string is a palindrome

---

Greedy/Knapsack/newknapsak.java

create algorithm to solve knapsak problem

knapsak.java

---

Branch and Bound/0_1 Knapsack/CPP/0_1Knapsack.cpp
Branch and Bound/0_1 Knapsack/README.md
Branch and Bound/README.md
README.md

Updated Branch and Bound Algorithm with 0_1 Knapsack Problem in CPP.
Also inlcuded Readme files

Added Branch And Bound algorithm and 0_1Knapsack Problem

---

DP/Coin Change Problem/README.md

Added a README.md file to the coin change problem

Added description to coin change problem

---

DP/Recursive_Staircase_Problem/README.md
README.md

Added a description to the recursive staircase problem
Added an entry in the table of contents in the main README.md file

Added description to recursive staircase problem

---

Graph/Diameter_of_tree/Diameter_of_tree.cpp

C++ code to find Diameter of tree.

Create Diameter of tree

---

Sorting/QuickSort/PHP/Quicksort.php

Add Umme Ammara to Contributors list

---

Graph/DijkstrasSPT/Dijkstra.cs

Add DijkstrasSPT in C#

---

BitManipulation/copy_set_bits_in_a_range/copy_set_bits_in_a_range.cpp
BitManipulation/count_number_of_bits_to_be_flipped_to_convert_a_to_b/count_number_of_bits_to_be_flipped_to_convert_a_to_b.cpp

added new problems solution in the BitManipulation directory

BitManipulation Problem

---

Math/largest_number_divisible_by_three/C++/LargestNumberDivisibleByThree.cpp
Math/largest_number_divisible_by_three/README.md

Add C++ solution, fix problem statement and sample output

Largest Number Divisible by Three

---

DP/Rod cutting/rod_cutting.cpp

Added rod cutting algo in the dp

Added rod cutting algo in the dp

---

DP/Maximum continuous subarray with index/max-continuous-subarrays.c

Add Thtiiz

---

Graph/TopoSort/Python/Kahn_Algorithm.py

Added implementation of Kahn's algorithm in python

Added Kahn's Algorithm in python

---

Graph/Weighted_Quick_Union/weighted_quick_union.cpp

It is an algorithm by Robert Sedgewick. It solves problems related to components or disjoint set.

Added a new Algorithm Weighted Quick Union

---

Data Structures/wavelet_tree/wavelt_tree.cpp

Add wavelet tree

---

String/suffix_array/suffix_array.cpp

This PR adds Suffix array Algorithm.

Add suffix array to strings

---

Math/Wilson's Theorem/Wilson's Theorem.cpp

This pull request adds Wilson's Theorem Algorithm

Update Math/Wilson's Theorem/Wilson's Theorem.cpp

---

NetworkFlow/Hopkraft Karp/Hopkraft Karp.cpp

This pull request adds Hopkraft Karp algorithm.

Update NetworkFlow/Hopkraft Karp/Hopkraft Karp.cpp

---

Math/last_digit_exp/JavaScript/LastDigitOfExp.js

I implemented the same algorithm as the readme and also added some test cases in the script.

 Added last digit of exp javascript

---

Sorting/QuickSort/Kotlin/QuickSort.kt

I added a program in kotlin directory in sorting directory , it is a quick sort program written in kotlin.

add quick sort program written in kotlin

---

Sorting/Selection Sort/C#/Program.cs

Added a C# code to the Selection Sort Algorithm folder.

Added C# version of Selection Sort algorithm

---

Sorting/TreeSort/Java/TreeSort.java
Sorting/TreeSort/JavaScript/TreeSort.js

TreeSort implementation in Java

Committed TreeSort.java

---

DP/WeightedJobScheduling/README.md
DP/WeightedJobScheduling/weighted_job_scheduling.cpp

Added weighted job scheduling algorithm in dp folder

Added weighted job scheduling in dp section

---

Geometry 2D/Lines Intersection/collinear_check.cpp

c++ program to check whether three points are collinear or not.

Create col linear_check.cpp

---

Math/UsefulFunctions/Math.cpp

Added some Useful implemented functions perfectly optimized in terms of complexity

Useful Implemented Functions
